___
___

# NumPy Exercises 

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions.

#### Import NumPy as np

In [2]:
import numpy as np

#### Create an array of 10 zeros 

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Create an array of 10 ones

In [4]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Create an array of 10 fives

In [7]:
a = np.ones(10)
a *5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### Create an array of the integers from 10 to 50

In [9]:
b = np.arange(10,51)
b

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Create an array of all the even integers from 10 to 50

In [10]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [11]:
np.arange(11,51,2)

array([11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43,
       45, 47, 49])

#### Create a 3x3 matrix with values ranging from 0 to 8

In [12]:
np.array(([0,1,2],[3,4,5],[6,7,8]))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [16]:
c = np.arange(0,9)
d=c.reshape(3,3)

In [17]:
d

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Create a 3x3 identity matrix

In [18]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Use NumPy to generate a random number between 0 and 1

In [19]:
np.random.rand(1)

array([0.18597398])

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [24]:
np.random.randn(25)

array([ 0.94084113,  0.60325334,  0.37502661,  0.74672215, -0.03460223,
        0.03168189,  1.08200881, -0.05731399,  2.03714932, -0.98001347,
       -0.40950561, -0.32418837,  1.09626695,  0.22959759,  0.34401352,
       -1.70230749, -0.31214916, -1.64131078, -0.77826634,  0.72198578,
       -1.15801953, -0.48704746, -1.02955775, -1.10225432, -0.45328278])

In [23]:
np.random.normal(0,1,25)

array([-0.70392411, -0.71374706,  0.08992806, -0.01102353, -0.25204433,
        1.66494943,  0.19131414,  1.96455056,  0.3277305 ,  0.45821123,
       -0.43501549,  0.92862085, -0.57333215, -0.3564923 , -0.53980323,
        0.45281664,  0.8941829 ,  1.46527733, -1.45365794,  2.46314016,
        0.00416058,  0.0437772 , -0.17907912,  0.51011909,  1.79136421])

#### Create the following matrix:

In [6]:
np.random.rand(10,9)

array([[0.2337792 , 0.26674623, 0.32074872, 0.89565743, 0.55018871,
        0.82922165, 0.0401348 , 0.18968655, 0.15613257],
       [0.58640905, 0.16735087, 0.44301488, 0.04947333, 0.22530615,
        0.23924214, 0.74573826, 0.91098796, 0.1043441 ],
       [0.24368252, 0.4300377 , 0.99272916, 0.31680496, 0.33346196,
        0.4821365 , 0.20655578, 0.37509473, 0.97743585],
       [0.94109917, 0.28248897, 0.84454905, 0.20571245, 0.54975   ,
        0.63474692, 0.87698202, 0.20042931, 0.22943042],
       [0.69509393, 0.02721815, 0.90806932, 0.78500417, 0.19002825,
        0.61551521, 0.28715846, 0.36319629, 0.80579488],
       [0.927043  , 0.14591217, 0.00934742, 0.7211872 , 0.90786282,
        0.72399836, 0.14321   , 0.04110482, 0.09474104],
       [0.75018365, 0.92127946, 0.44847712, 0.26895087, 0.40871125,
        0.26003009, 0.01322554, 0.01094022, 0.64844071],
       [0.23975737, 0.96296139, 0.15529996, 0.47249613, 0.96185943,
        0.46510099, 0.17381092, 0.07715181, 0.55827428],


#### Create an array of 20 linearly spaced points between 0 and 1:

In [10]:
np.random.randn(1,21)

array([[-0.32210209,  0.1749827 , -1.43592833,  1.61413076, -1.41593508,
        -0.24884554,  1.82373251, -0.07832982,  1.42113992,  0.86139125,
        -0.16260171, -0.50080316, -0.48401243,  0.09894636,  0.83099731,
        -2.62232571, -0.85862225, -0.77432471,  0.00353457, -1.06252172,
         0.56698476]])

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [11]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [11]:
mat[3,4]

20

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [26]:
print(mat[1,1])
print(mat[2,1])
print(mat[3,1])

7
12
17


In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [17]:
mat[4]

array([21, 22, 23, 24, 25])

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [19]:
mat[3:5]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Now do the following

#### Get the sum of all the values in mat

In [ ]:
mat.sum()

325

#### Get the standard deviation of the values in mat

In [ ]:
np.std(mat,axis=0)

7.2111025509279782

#### Get the sum of all the columns in mat

In [30]:
np.sum(mat,axis=0)

array([55, 60, 65, 70, 75])

# Great Job!